### ISSUE TITLE
Ability to skip pages while collecting bundles

### ISSUE THREAD

**Issue by koentjeh** [magesuite/magepack#101]
We have a site without a checkout. Customers can make an appointment directly on the product page. This leads to a webshop without a checkout page nor cart.

When trying to generate a bundle config the collecting process leads to an error because it can't add a product to the cart because the cart doesn't exists.

It would be nice to have a feature to skip the checkout page with an option `--skip-checkout` or that an error does not lead to a complete stop but rather an error message, like the success messages below.

```
ℹ Collecting bundle modules in the browser.                                                                                                                                                                   10:06:57
ℹ Collecting modules for bundle "category".                                                                                                                                                                   10:06:57
✔ Finished collecting modules for bundle "category".                                                                                                                                                          10:07:08
ℹ Collecting modules for bundle "cms".                                                                                                                                                                        10:07:08
✔ Finished collecting modules for bundle "cms".                                                                                                                                                               10:07:17
ℹ Collecting modules for bundle "product".                                                                                                                                                                    10:07:17
✔ Finished collecting modules for bundle "product".                                                                                                                                                           10:07:26
ℹ Collecting modules for bundle "checkout".                                                                                                                                                                   10:07:26

 ERROR  Evaluation failed: TypeError: Cannot read property 'submit' of null                                                                                                                                   10:07:29
    at __puppeteer_evaluation_script__:2:62

  at __puppeteer_evaluation_script__:2:62
  at ExecutionContext._evaluateInternal (node_modules/puppeteer/lib/ExecutionContext.js:122:13)
  at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
  at ExecutionContext.<anonymous> (node_modules/puppeteer/lib/helper.js:111:15)
  at DOMWorld.evaluate (node_modules/puppeteer/lib/DOMWorld.js:112:20)
  at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
  at Frame.<anonymous> (node_modules/puppeteer/lib/helper.js:111:15)
  at Page.evaluate (node_modules/puppeteer/lib/Page.js:860:43)
  at Page.<anonymous> (node_modules/puppeteer/lib/helper.js:112:23)
  at Object.checkout (lib/generate/collector/checkout.js:77:14)
  at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by robhuijben** [comment]
I would like to see this implemented too. We're using Magento as a catalog platform in several projects, so this would be a great option too be able to still use Magepack.
