### ISSUE TITLE
ERROR  Navigation timeout of 30000 ms exceeded. Not compatible with Athlete 2 Theme?

### ISSUE THREAD

**Issue by elfeffe** [magesuite/magepack#11]
I'm using this theme https://athlete2.com/us/alvord-10-ws-mens-trail-running-shoes.html on Magento 2.3.4 with the patch for mixins.

It seems to work, but when I tries to add checkout I get:

ℹ Collecting bundle modules in the browser.                                                                       16:24:46
ℹ Collecting modules for bundle "category".                                                                       16:24:46
✔ Finished collecting modules for bundle "category".                                                              16:24:57
ℹ Collecting modules for bundle "cms".                                                                            16:24:57
✔ Finished collecting modules for bundle "cms".                                                                   16:25:07
ℹ Collecting modules for bundle "product".                                                                        16:25:07
✔ Finished collecting modules for bundle "product".                                                               16:25:18
ℹ Collecting modules for bundle "checkout".                                                                       16:25:18

 ERROR  Navigation timeout of 30000 ms exceeded                                                                   16:26:05

  at /usr/local/share/.config/yarn/global/node_modules/puppeteer/lib/LifecycleWatcher.js:142:21
  -- ASYNC --
  at Frame.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/puppeteer/lib/helper.js:111:15)
  at Page.goto (/usr/local/share/.config/yarn/global/node_modules/puppeteer/lib/Page.js:672:49)
  at Page.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/puppeteer/lib/helper.js:112:23)
  at Object.checkout (/usr/local/share/.config/yarn/global/node_modules/magepack/lib/generate/collector/checkout.js:65:16)
  at runMicrotasks (<anonymous>)
  at processTicksAndRejections (internal/process/task_queues.js:97:5)
  at async module.exports (/usr/local/share/.config/yarn/global/node_modules/magepack/lib/generate.js:23:13) 

Checkout page doesn't take 30 seconds to load, so it may be some html problem. No?

**Comment by elfeffe** [comment]
It works on live server, not in my local but works on live server

**Comment by beyondmedia** [comment]
Magento tends to be very slow on local machines.

Can we add 
    
> await page.setDefaultNavigationTimeout(0); 

to collectors? 
Or set the timeout directly to 0 in the goto function. 

In our current setup we would generate the magepack.config.js with a pre commit hook, then our build server doesn't need a full functional shop.

**Comment by beyondmedia** [comment]
@krzksz Do you see any problems with infinite timeout for the generation?

**Comment by krzksz** [comment]
I'm not really into allowing it to wait forever, but maybe something like 60s only for initial opening of the page would be enough?

**Comment by beyondmedia** [comment]
Can't really tell as some enviroments are really slow. To be save i would suggest 120.

**Comment by LucasMali** [comment]
> It works on live server, not in my local but works on live server

I'm having the opposite, it works locally but not on the dev server.

**Comment by maderlock** [comment]
I've had to manually edit the timeouts because I want to use magepack to speed up a very slow site... which means that timeouts might be exceeded! We've had to edit:
1. /usr/local/lib/node_modules/magepack/node_modules/puppeteer/lib/DOMWorld.js, line 454:
change line: return new WaitTask(this, pageFunction, 'function', polling, 3000, ...args).promise;
to: return new WaitTask(this, pageFunction, 'function', polling, 0, ...args).promise;
2. /usr/local/lib/node_modules/magepack/node_modules/puppeteer/lib/Page.js, line: 672:
add new line with code "options.timeout = 0;" before "return await this._frameManager.mainFrame().goto(url, options);"
3. /usr/local/lib/node_modules/magepack/node_modules/puppeteer/lib/Page.js, line: 693:
add new line with code "options.timeout = 0;" before "return await this._frameManager.mainFrame().waitForNavigation(options);"

The pity of this is that we can't so easily add this to our workflow as we cannot use the docker image that was made without figuring out how to do the above patches via command line calls.

**Comment by bselimb** [comment]
> I've had to manually edit the timeouts because I want to use magepack to speed up a very slow site... which means that timeouts might be exceeded! We've had to edit:
> 
> 1. /usr/local/lib/node_modules/magepack/node_modules/puppeteer/lib/DOMWorld.js, line 454:
>    change line: return new WaitTask(this, pageFunction, 'function', polling, 3000, ...args).promise;
>    to: return new WaitTask(this, pageFunction, 'function', polling, 0, ...args).promise;
> 2. /usr/local/lib/node_modules/magepack/node_modules/puppeteer/lib/Page.js, line: 672:
>    add new line with code "options.timeout = 0;" before "return await this._frameManager.mainFrame().goto(url, options);"
> 3. /usr/local/lib/node_modules/magepack/node_modules/puppeteer/lib/Page.js, line: 693:
>    add new line with code "options.timeout = 0;" before "return await this._frameManager.mainFrame().waitForNavigation(options);"
> 
> The pity of this is that we can't so easily add this to our workflow as we cannot use the docker image that was made without figuring out how to do the above patches via command line calls.

This is for `  waiting for function failed: timeout 30000ms exceeded` error, FYI. Navigation error is different and @LucasMali 's solution works for that. 

I'm testing @maderlock 's solution now to see if it works, been a while on terminal now.
