### ISSUE TITLE
JS Error after bundle: Mismatched anonymous define() module: function return function (target)

### ISSUE THREAD

**Issue by in-session** [magesuite/magepack#130]
Are there any problems with the current RequireJS / mixing version?
https://github.com/magento/magento2/blob/2.4-develop/lib/web/requirejs/require.js

Magento ver. 2.4.3-p1
Magepack vers. latest

![Ashampoo_Snap_Mittwoch, 8  Dezember 2021_09h46m45s_009_](https://user-images.githubusercontent.com/16542619/145184465-f9a04f24-5992-4bce-a4a8-636e5dba6c17.png)

```

Uncaught Error: Mismatched anonymous define() module: function () {
        return function (target) {
            return target;
        }
    }
https://requirejs.org/docs/errors.html#mismatch
    at makeError (require.js:168)
    at intakeDefines (require.js:1254)
    at localRequire (require.js:1446)
    at Object.load (mixins.js:128)
    at Module.<anonymous> (require.js:1095)
    at require.js:134
    at on (require.js:517)
    at Module.callPlugin (require.js:955)
    at Module.fetch (require.js:824)
    at Module.check (require.js:856)
makeError @ require.js:168
intakeDefines @ require.js:1254
localRequire @ require.js:1446
load @ mixins.js:128
(anonym) @ require.js:1095
(anonym) @ require.js:134
on @ require.js:517
callPlugin @ require.js:955
fetch @ require.js:824
check @ require.js:856
enable @ require.js:1176
enable @ require.js:1557
(anonym) @ require.js:1161
(anonym) @ require.js:134
each @ require.js:59
enable @ require.js:1113
init @ require.js:788
callGetModule @ require.js:1203
intakeDefines @ require.js:1259
localRequire @ require.js:1446
load @ mixins.js:128
(anonym) @ require.js:1095
(anonym) @ require.js:134
on @ require.js:517
callPlugin @ require.js:955
fetch @ require.js:824
check @ require.js:856
enable @ require.js:1176
enable @ require.js:1557
(anonym) @ require.js:1161
(anonym) @ require.js:134
each @ require.js:59
enable @ require.js:1113
enable @ require.js:1557
(anonym) @ require.js:1161
(anonym) @ require.js:134
each @ require.js:59
enable @ require.js:1113
init @ require.js:788
callGetModule @ require.js:1203
intakeDefines @ require.js:1259
localRequire @ require.js:1446
load @ mixins.js:128
(anonym) @ require.js:1095
(anonym) @ require.js:134
on @ require.js:517
callPlugin @ require.js:955
fetch @ require.js:824
check @ require.js:856
enable @ require.js:1176
enable @ require.js:1557
(anonym) @ require.js:1161
(anonym) @ require.js:134
each @ require.js:59
enable @ require.js:1113
enable @ require.js:1557
(anonym) @ require.js:1161
(anonym) @ require.js:134
each @ require.js:59
enable @ require.js:1113
enable @ require.js:1557
(anonym) @ require.js:1161
(anonym) @ require.js:134
each @ require.js:59
enable @ require.js:1113
init @ require.js:788
callGetModule @ require.js:1203
intakeDefines @ require.js:1259
localRequire @ require.js:1446
load @ mixins.js:128
(anonym) @ require.js:1095
(anonym) @ require.js:134
on @ require.js:517
callPlugin @ require.js:955
fetch @ require.js:824
check @ require.js:856
enable @ require.js:1176
enable @ require.js:1557
(anonym) @ require.js:1161
(anonym) @ require.js:134
each @ require.js:59
enable @ require.js:1113
init @ require.js:788
callGetModule @ require.js:1203
intakeDefines @ require.js:1259
localRequire @ require.js:1446
load @ mixins.js:128
(anonym) @ require.js:1095
(anonym) @ require.js:134
on @ require.js:517
callPlugin @ require.js:955
fetch @ require.js:824
check @ require.js:856
enable @ require.js:1176
enable @ require.js:1557
(anonym) @ require.js:1161
(anonym) @ require.js:134
each @ require.js:59
enable @ require.js:1113
enable @ require.js:1557
(anonym) @ require.js:1161
(anonym) @ require.js:134
each @ require.js:59
enable @ require.js:1113
init @ require.js:788
callGetModule @ require.js:1203
completeLoad @ require.js:1590
onScriptLoad @ require.js:1717
load (async)
req.load @ require.js:1942
load @ require.js:1685
load @ require.js:834
fetch @ require.js:824
check @ require.js:856
enable @ require.js:1176
enable @ require.js:1557
(anonym) @ require.js:1161
(anonym) @ require.js:134
each @ require.js:59
enable @ require.js:1113
init @ require.js:788
(anonym) @ require.js:1460
setTimeout (async)
req.nextTick @ require.js:1815
localRequire @ require.js:1449
configure @ require.js:1387
requirejs @ require.js:1794
req.config @ require.js:1805
(anonym) @ requirejs-config.js:76
(anonym) @ requirejs-config.js:77
(anonym) @ requirejs-config.js:2126
78 weitere Frames anzeigen
```

**Comment by Jupagar77** [comment]
Hi @in-session  
Having same problem here, did you find a solution?

**Comment by igi8819** [comment]
We have the same issue.

**Comment by fredden** [comment]
This is probably to do with the anonymous AMD detection. Are you still getting the error with magepack version 2.11.2?

**Comment by ntmhung** [comment]
yes mate, the error still occurs with magepack version 2.11.2

**Comment by ArthurMenegoli** [comment]
Magento 2.4.6
Magepack 2.11.2

Error still occurs.

Funny how I have a mirror store on same versions that runs the compilation with no problems.


```

ℹ Collecting modules for bundle "category".                                                                                13:39:12
 ERROR  Evaluation failed: Error: Mismatched anonymous define() module: function(){return fun ............
https://requirejs.org/docs/errors.html#mismatch
    at makeError (https://www.store.com.br/static/_cache/merged/df181248993a53edc44adc34eb624726.min.js:17:53)
    at intakeDefines (https://www.store.com.br/static/_cache/merged/df181248993a53edc44adc34eb624726.min.js:81:132)
    at localRequire (https://www.store.com.br/static/_cache/merged/df181248993a53edc44adc34eb624726.min.js:104:1)
    at Object.defContext.require (https://www.store.com.br/static/_cache/merged/df181248993a53edc44adc34eb624726.min.js:190:401)
    at requirejs (https://www.store.com.br/static/_cache/merged/df181248993a53edc44adc34eb624726.min.js:123:16)
    at __puppeteer_evaluation_script__:3:17
    at new Promise (<anonymous>)
    at __puppeteer_evaluation_script__:2:13

  https://requirejs.org/docs/errors.html#mismatch
  at makeError (https://www.store.com.br/static/_cache/merged/df181248993a53edc44adc34eb624726.min.js:17:53)
  at intakeDefines (https://www.store.com.br/static/_cache/merged/df181248993a53edc44adc34eb624726.min.js:81:132)
  at localRequire (https://www.store.com.br/static/_cache/merged/df181248993a53edc44adc34eb624726.min.js:104:1)
  at Object.defContext.require (https://www.store.com.br/static/_cache/merged/df181248993a53edc44adc34eb624726.min.js:190:401)
  at requirejs (https://www.store.com.br/static/_cache/merged/df181248993a53edc44adc34eb624726.min.js:123:16)
  at __puppeteer_evaluation_script__:3:17
  at new Promise (<anonymous>)
  at __puppeteer_evaluation_script__:2:13
  at ExecutionContext._evaluateInternal (/usr/local/lib/node_modules/magepack/node_modules/puppeteer/lib/ExecutionContext.js:122:13)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async ExecutionContext.evaluate (/usr/local/lib/node_modules/magepack/node_modules/puppeteer/lib/ExecutionContext.js:48:12)
  at async module.exports (/usr/local/lib/node_modules/magepack/lib/generate/collectModules.js:17:5)
  at async Object.category (/usr/local/lib/node_modules/magepack/lib/generate/collector/category.js:43:33)
  at async module.exports (/usr/local/lib/node_modules/magepack/lib/generate.js:28:13)
  -- ASYNC --
  at ExecutionContext.<anonymous> (/usr/local/lib/node_modules/magepack/node_modules/puppeteer/lib/helper.js:111:15)
  at DOMWorld.evaluate (/usr/local/lib/node_modules/magepack/node_modules/puppeteer/lib/DOMWorld.js:112:20)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  -- ASYNC --
  at Frame.<anonymous> (/usr/local/lib/node_modules/magepack/node_modules/puppeteer/lib/helper.js:111:15)
  at Page.evaluate (/usr/local/lib/node_modules/magepack/node_modules/puppeteer/lib/Page.js:860:43)
  at Page.<anonymous> (/usr/local/lib/node_modules/magepack/node_modules/puppeteer/lib/helper.js:112:23)
  at module.exports (/usr/local/lib/node_modules/magepack/lib/generate/collectModules.js:17:16)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async Object.category (/usr/local/lib/node_modules/magepack/lib/generate/collector/category.js:43:33)
  at async module.exports (/usr/local/lib/node_modules/magepack/lib/generate.js:28:13)

```

**Comment by fredden** [comment]
@ArthurMenegoli can you share some more information about the store? I tried visiting https://www.store.com.br/, but this doesn't look like a Magento instance to me. It's curious that you have one working and one broken website. Can you work out what's different between these that causes a problem?

**Comment by in-session** [comment]
> Hi @in-session Having same problem here, did you find a solution?

@Jupagar77 
No, as we are concentrating on Hyva, I have not pursued this any further.
