### ISSUE TITLE
ERROR  Failed to launch the browser process!

### ISSUE THREAD

**Issue by alexsmith2709** [magesuite/magepack#133]
I am using the latest magepack and magento 2.4.3-p1 on a ubuntu 20.04 server and it was all working fine, then i noticed that i was getting 404 errors for bundle-common.min.js and bundle-product.min.js so i thought i would run a generate again but when doing so i get the error:
`[1852540:1852540:0117/165642.700013:ERROR:browser_main_loop.cc(1512)] Unable to open X display.

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

  [1852540:1852540:0117/165642.700013:ERROR:browser_main_loop.cc(1512)] Unable to open X display.

  TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

  at onClose (/usr/local/lib/node_modules/magepack/node_modules/puppeteer/lib/Launcher.js:750:14)
  at ChildProcess.<anonymous> (/usr/local/lib/node_modules/magepack/node_modules/puppeteer/lib/Launcher.js:740:61)
  at ChildProcess.emit (node:events:402:35)
  at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)`
How can i solve this? All the dependencies were installed as it was working fine for a couple days

**Comment by taintedstephen** [comment]
This quick guide worked for me: https://medium.com/@ssmak/how-to-fix-puppetteer-error-while-loading-shared-libraries-libx11-xcb-so-1-c1918b75acc3

Essentially you install some extra required components.

**Comment by ishaqdahot** [comment]
I have also the same issue.
I have installed all necessary dependencies and `ldd /usr/lib/node_modules/magepack/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome | grep not` showing nothing 
I am using Magento 2.4.3-p1 with Ubuntu
