### ISSUE TITLE
magepack generate is hanging and on debug showing error

### ISSUE THREAD

**Issue by ishaqdahot** [magesuite/magepack#144]
On Magento 2.4.3-p2 with all required extensions installed as required by puppeteer but it is showing an error.

` ERROR  Failed to launch the browser process!                                                                                       15:17:39
[3317520:3317520:0619/151739.394395:ERROR:browser_main_loop.cc(1512)] Unable to open X display.

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

  [3317520:3317520:0619/151739.394395:ERROR:browser_main_loop.cc(1512)] Unable to open X display.

  TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

  at onClose (/usr/lib/node_modules/magepack/node_modules/puppeteer/lib/Launcher.js:750:14)
  at ChildProcess.<anonymous> (/usr/lib/node_modules/magepack/node_modules/puppeteer/lib/Launcher.js:740:61)
  at ChildProcess.emit (node:events:538:35)
  at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
`

I have checked which dependencies are missing through `ldd /usr/lib/node_modules/magepack/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome | grep not` and there is no outup means all are installed.

What may be the reason?

I am using Ubuntu and there are no errors in the browser console also.

**Comment by deedy-tech** [comment]
@ishaqdahot - Did you find out what was causing the issue as I am hitting the same problem on Magento 2.4.4-p2

**Comment by petarBozovic** [comment]
I'm having this same issue. anyone out theree
