### ISSUE TITLE
Issue with JS after update to 2.11.2 

### ISSUE THREAD

**Issue by trongnd90** [magesuite/magepack#169]
Uncaught Error: Mismatched anonymous define() module: function(){"use strict";return window.Swiper}
http://requirejs.org/docs/errors.html#mismatch
    at makeError (require.min.js:16:53)
    at intakeDefines (require.min.js:77:132)
    at localRequire (require.min.js:97:1)
    at Object.load (mixins.min.js:8:135)
    at Module.<anonymous> (require.min.js:71:105)
    at require.min.js:11:51
    at on (require.min.js:40:147)
    at Module.callPlugin (require.min.js:61:264)
    at Module.fetch (require.min.js:55:269)
    at Module.check (require.min.js:56:125)
    
 After updating our magepack to the version 2.11.2 we were facing the error above. After rolling back to 2.10.1 the error has gone.
Magento version: 2.4.2-p2

**Comment by fredden** [comment]
@trongnd90 please can you provide a link to a website with the problem so that we can investigate this further? (Ideally with Magepack enabled and merged JavaScript disabled. A non-production website is fine.) Does the problem occur during the bundling or generation phases?
