### ISSUE TITLE
@jridgewell/gen-mapping error

### ISSUE THREAD

**Issue by arjunadobe** [magesuite/magepack#185]
`Suddenly i am getting this error    

 W: /app/.nvm/versions/node/v10.24.1/lib/node_modules/magepack/node_modules/@jridgewell/gen-mapping/dist/gen-mapping.umd.js:1328

    W:             const originalLine = originalSource[sourceLine] ||= [];

    W:                                                               ^

    W: 

    W: SyntaxError: Unexpected token =

    W:     at Module._compile (internal/modules/cjs/loader.js:723:23)

    W:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

    W:     at Module.load (internal/modules/cjs/loader.js:653:32)

    W:     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)

    W:     at Function.Module._load (internal/modules/cjs/loader.js:585:3)

    W:     at Module.require (internal/modules/cjs/loader.js:692:17)

    W:     at require (internal/modules/cjs/helpers.js:25:18)

    W:     at Object.<anonymous> (/app/.nvm/versions/node/v10.24.1/lib/node_modules/magepack/node_modules/@jridgewell/source-map/dist/source-map.cjs:6:18)

    W:     at Module._compile (internal/modules/cjs/loader.js:778:30)

    W:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)`

**Comment by arjunadobe** [comment]
Mostly its related to this https://github.com/jridgewell/sourcemaps/issues/23

**Comment by arjunadobe** [comment]
Now the issue was solved. https://github.com/jridgewell/sourcemaps/issues/23  fixed the issue.

**Comment by arjunadobe** [comment]
Closing the ticket
