### ISSUE TITLE
HTTP Auth Support

### ISSUE THREAD

**Issue by roma-glushko** [magesuite/magepack#19]
Thank you for the great tool <3

We are using HTTP auth on the dev environment and it seems like this can trigger the following issue:

```js
ℹ Collecting bundle modules in the browser.                                                                                                                                           12:50:04
ℹ Collecting modules for bundle "category".                                                                                                                                           12:50:04

 ERROR  Evaluation failed: TypeError: require is not a function                                                                                                                       12:50:08
    at __puppeteer_evaluation_script__:3:17
    at new Promise (<anonymous>)
    at __puppeteer_evaluation_script__:2:13

  at __puppeteer_evaluation_script__:3:17
  at new Promise (<anonymous>)
  at __puppeteer_evaluation_script__:2:13
  at ExecutionContext._evaluateInternal (/usr/local/share/.config/yarn/global/node_modules/puppeteer/lib/ExecutionContext.js:122:13)
  at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
  at ExecutionContext.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/puppeteer/lib/helper.js:111:15)
  at DOMWorld.evaluate (/usr/local/share/.config/yarn/global/node_modules/puppeteer/lib/DOMWorld.js:112:20)
  at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
  at Frame.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/puppeteer/lib/helper.js:111:15)
  at Page.evaluate (/usr/local/share/.config/yarn/global/node_modules/puppeteer/lib/Page.js:860:43)
  at Page.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/puppeteer/lib/helper.js:112:23)
  at module.exports (/usr/local/share/.config/yarn/global/node_modules/magepack/lib/generate/collectModules.js:19:16)
  at process._tickCallback (internal/process/next_tick.js:68:7)
```

I have tried to use https://user:pass@url.com format for links but got no luck with bypassing this.

It would be nice to support HTTP auth and let to run Megapack from similar dev setups.

**Comment by roma-glushko** [comment]
It's possible via additional params in the generate command:

```bash
magepack generate -u httpUser -p httpPwd --cms-url="{{CMS_PAGE_URL}}" --category-url="{{CATEGORY_PAGE_URL}}" --product-url="{{PRODUCT_PAGE_URL}}"
```
Leaving this information as a reference for others and closing the issue
