### ISSUE TITLE
Dockerfile to ease execution

### ISSUE THREAD

**Issue by phoenix-bjoern** [magesuite/magepack#27]
It would be handy to have a Dockerfile (and maybe eaven a Docker image on Docker Hub) to ease the execution of magepack. There are some dependecies like npm and puppeteer which make it a bit tricky to execute magepack - at least in your build pipeline. Having a Docker file (which requires a Dockerfile) which already has all necessary dependencies would make it much simpler to setup and execute magepack.
Beside the npm installation it would be great if you could already support environment variables for cms/product/category URLs.

**Comment by Hector68** [comment]
It`s a good idea. I have created  a docker image for my project. https://hub.docker.com/repository/docker/hector68/magepack Evry one can try it

**Comment by Hector68** [comment]
If it can help, I will publish a Dockerfile

`FROM node:12-slim

RUN apt-get update \
    && apt-get install -y wget gnupg \
    && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
    && apt-get update \
    && apt-get install -y google-chrome-unstable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf \
      --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

RUN npm install magepack

RUN mkdir magento && cd magento
WORKDIR /magento
VOLUME /magento

ENTRYPOINT ["node", "../node_modules/magepack/cli.js"]`

**Comment by maderlock** [comment]
Thanks for putting this up. I need to update some timeouts in magepack though. Any idea how I would go about using the dockerfile with a checked out version of the github repo?

**Comment by maderlock** [comment]
I've managed to use the docker image on OS X to run bundle, but when I attempt to run this on our production servers (AWS linux) I run the following:

    docker run -it --user 1009:1009 -v /var/www/vhosts/blah/deploy/release-candidate/:/magento hector68/magepack bundle

The output comes out as:

    ℹ Using bundling config from "/magento/magepack.config.js".                                                                                                                                                                                                                                     
    13:35:46
    ℹ Creating bundles for "pub/static/frontend/Blah/Usa/en_GB".                                                                                                                                                                                                                                
    13:35:46
    
     ERROR  ENOENT: no such file or directory, mkdir 
    'pub/static/frontend/Blah/Usa/en_GB/magepack'                                                                                                                                                                                              
    13:35:52
    
      at Object.mkdirSync (fs.js:840:3)
      at /node_modules/magepack/lib/bundle.js:124:20
      at Array.forEach (<anonymous>)
      at /node_modules/magepack/lib/bundle.js:27:24
      at Array.forEach (<anonymous>)
      at module.exports (/node_modules/magepack/lib/bundle.js:24:18)
      at Command.<anonymous> (/node_modules/magepack/cli.js:47:32)
      at Command.listener [as _actionHandler] (/node_modules/commander/index.js:413:31)
      at Command._parseCommand (/node_modules/commander/index.js:914:14)
      at Command._dispatchSubcommand (/node_modules/commander/index.js:865:18)

**Comment by rwky** [comment]
I've added an automated build docker image https://hub.docker.com/r/rwky/magepack
