### ISSUE TITLE
BASE_URL is not defined for checkout page

### ISSUE THREAD

**Issue by VasiliyDP** [magesuite/magepack#48]
During `magepack generate --cms-url="{{CMS_PAGE_URL}}" --category-url="{{CATEGORY_PAGE_URL}}" --product-url="{{PRODUCT_PAGE_URL}}"` Got an error:

`
ℹ Collecting bundle modules in the browser.                                                                                                                                                     13:15:49
ℹ Collecting modules for bundle "category".                                                                                                                                                     13:15:49
✔ Finished collecting modules for bundle "category".                                                                                                                                            13:16:02
ℹ Collecting modules for bundle "cms".                                                                                                                                                          13:16:02
✔ Finished collecting modules for bundle "cms".                                                                                                                                                 13:16:12
ℹ Collecting modules for bundle "product".                                                                                                                                                      13:16:12
✔ Finished collecting modules for bundle "product".                                                                                                                                             13:16:23
ℹ Collecting modules for bundle "checkout".                                                                                                                                                     13:16:23

 ERROR  Evaluation failed: ReferenceError: BASE_URL is not defined                                                                                                                              13:16:31
    at __puppeteer_evaluation_script__:1:8

  at __puppeteer_evaluation_script__:1:8
  at ExecutionContext._evaluateInternal (/usr/local/lib/node_modules/magepack/node_modules/puppeteer/lib/ExecutionContext.js:122:13)
  at runMicrotasks (<anonymous>)
  at processTicksAndRejections (internal/process/task_queues.js:94:5)
  at async ExecutionContext.evaluate (/usr/local/lib/node_modules/magepack/node_modules/puppeteer/lib/ExecutionContext.js:48:12)
  at async Object.checkout (/usr/local/lib/node_modules/magepack/lib/generate/collector/checkout.js:63:21)
  at async module.exports (/usr/local/lib/node_modules/magepack/lib/generate.js:24:13)
  -- ASYNC --
  at ExecutionContext.<anonymous> (/usr/local/lib/node_modules/magepack/node_modules/puppeteer/lib/helper.js:111:15)
  at DOMWorld.evaluate (/usr/local/lib/node_modules/magepack/node_modules/puppeteer/lib/DOMWorld.js:112:20)
  at runMicrotasks (<anonymous>)
  at processTicksAndRejections (internal/process/task_queues.js:94:5)
  -- ASYNC --
  at Frame.<anonymous> (/usr/local/lib/node_modules/magepack/node_modules/puppeteer/lib/helper.js:111:15)
  at Page.evaluate (/usr/local/lib/node_modules/magepack/node_modules/puppeteer/lib/Page.js:860:43)
  at Page.<anonymous> (/usr/local/lib/node_modules/magepack/node_modules/puppeteer/lib/helper.js:112:23)
  at Object.checkout (/usr/local/lib/node_modules/magepack/lib/generate/collector/checkout.js:63:32)
  at runMicrotasks (<anonymous>)
  at processTicksAndRejections (internal/process/task_queues.js:94:5)
  at async module.exports (/usr/local/lib/node_modules/magepack/lib/generate.js:24:13)
`

Locally fixed it by adding static url here magepack/lib/generate/collector/checkout.js:63 `const baseUrl = "https://mysite.test/";`

**Comment by tuyennn** [comment]
+1
