### ISSUE TITLE
net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by ravibhalodia** [magesuite/magepack#52]
Hello team, 

I am getting following error when running magepack generate command

net::ERR_CONNECTION_REFUSED at https://domain name/index.php/women.html                             05:35:05

  at navigate (/usr/lib/node_modules/magepack/node_modules/puppeteer/lib/FrameManager.js:120:37)
  at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
  at Frame.<anonymous> (/usr/lib/node_modules/magepack/node_modules/puppeteer/lib/helper.js:111:15)
  at Page.goto (/usr/lib/node_modules/magepack/node_modules/puppeteer/lib/Page.js:672:49)
  at Page.<anonymous> (/usr/lib/node_modules/magepack/node_modules/puppeteer/lib/helper.js:112:23)
  at Object.category (/usr/lib/node_modules/magepack/lib/generate/collector/category.js:36:16)
  at process._tickCallback (internal/process/next_tick.js:68:7)

Any idea why I am getting this error? 

Thanks,

**Comment by krzksz** [comment]
Hey @ravibhalodia, did you try running magepack in debug mode? It looks like it is not able to reach your shop's URL or something.

**Comment by sarootua** [comment]
![image](https://user-images.githubusercontent.com/20066738/114032239-cb5e6c00-9884-11eb-9f23-b4ee3bfb2593.png)

**Comment by sarootua** [comment]
its developer mode - i have problem/ help me please

**Comment by jennie29** [comment]
I am facing the same problem and don't understand why it refused my local path 
![Screenshot from 2021-07-13 17-57-25](https://user-images.githubusercontent.com/55841011/125440489-48e2215b-51bb-4b48-ba45-530f2a09bcbb.png)

**Comment by phpWebStudio** [comment]
Same issue from inside Docker container. Ping of domain-name is well. Web-shop opened in browser as well.

**Comment by rzinovets** [comment]
you need to add docker container IP address to /etc/hosts.
to get ip: docker inspect \
  -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' container_name_or_id
  (it helped me!)
