### ISSUE TITLE
 ERROR  Failed to launch the browser process!    

### ISSUE THREAD

**Issue by Nafisa78** [magesuite/magepack#55]
I am getting error when i run magepack generate command.
How to solve this?
 ERROR  Failed to launch the browser process!                                                                                       07:46:13
/srv/.nvm/versions/node/v14.7.0/lib/node_modules/magepack/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

  /srv/.nvm/versions/node/v14.7.0/lib/node_modules/magepack/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory
  
  
  TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md
  
  at onClose (/srv/.nvm/versions/node/v14.7.0/lib/node_modules/magepack/node_modules/puppeteer/lib/Launcher.js:750:14)
  at Interface.<anonymous> (/srv/.nvm/versions/node/v14.7.0/lib/node_modules/magepack/node_modules/puppeteer/lib/Launcher.js:739:50)
  at Interface.emit (events.js:326:22)
  at Interface.close (readline.js:424:8)
  at Socket.onend (readline.js:202:10)
  at Socket.emit (events.js:326:22)
  at endReadableNT (_stream_readable.js:1244:12)
  at processTicksAndRejections (internal/process/task_queues.js:80:21)

**Comment by krzksz** [comment]
Hey, it seems like you're facing a known problem for Ubuntu. There is a number of results with solutions there: https://www.google.com/search?hl=pl&q=error%20while%20loading%20shared%20libraries%3A%20libX11%2Dxcb.so.1

**Comment by krzksz** [comment]
Closing this as it seems to be unrelated with Magepack itself.
