### ISSUE TITLE
Failed to install magepack, permission denied

### ISSUE THREAD

**Issue by gwharton** [magesuite/magepack#8]
```
root@dev:~# npm install -g magepack
npm WARN npm npm does not support Node.js v10.15.2
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
/usr/local/bin/magepack -> /usr/local/lib/node_modules/magepack/cli.js

> puppeteer@2.1.1 install /usr/local/lib/node_modules/magepack/node_modules/puppeteer
> node install.js

ERROR: Failed to download Chromium r722234! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
{ Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/magepack/node_modules/puppeteer/.local-chromium'
  -- ASYNC --
    at BrowserFetcher.<anonymous> (/usr/local/lib/node_modules/magepack/node_modules/puppeteer/lib/helper.js:111:15)
    at Object.<anonymous> (/usr/local/lib/node_modules/magepack/node_modules/puppeteer/install.js:66:16)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path:
   '/usr/local/lib/node_modules/magepack/node_modules/puppeteer/.local-chromium' }
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: puppeteer@2.1.1 (node_modules/magepack/node_modules/puppeteer):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: puppeteer@2.1.1 install: `node install.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ magepack@2.1.2
updated 1 package in 2.43s

```

**Comment by krzksz** [comment]
This doesn't seem to be an issue with Magepack but rather with `npm` and `node` versions mismatch: https://github.com/nodejs/help/issues/1877 Can you try updating both of them to newer releases?

**Comment by gwharton** [comment]
```
root@dev:~# npm -v
6.14.4
root@dev:~# node -v
v13.12.0
root@dev:~# npm install -g magepack
/usr/local/bin/magepack -> /usr/local/lib/node_modules/magepack/cli.js

> puppeteer@2.1.1 install /usr/local/lib/node_modules/magepack/node_modules/puppeteer
> node install.js

ERROR: Failed to download Chromium r722234! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/magepack/node_modules/puppeteer/.local-chromium'
  -- ASYNC --
    at BrowserFetcher.<anonymous> (/usr/local/lib/node_modules/magepack/node_modules/puppeteer/lib/helper.js:111:15)
    at Object.<anonymous> (/usr/local/lib/node_modules/magepack/node_modules/puppeteer/install.js:66:16)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/usr/local/lib/node_modules/magepack/node_modules/puppeteer/.local-chromium'
}
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: puppeteer@2.1.1 (node_modules/magepack/node_modules/puppeteer):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: puppeteer@2.1.1 install: `node install.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ magepack@2.1.2
updated 1 package in 2.736s

```

**Comment by gwharton** [comment]
installs ok if i don't install globally.

The command `mkdir '/usr/local/lib/node_modules/magepack/node_modules/puppeteer/.local-chromium'` is failing because the folder `/usr/local/lib/node_modules/magepack/node_modules/puppeteer` does not exist.

**Comment by krzksz** [comment]
Seems to be some kind of permissions issue on your machine, maybe related to https://github.com/puppeteer/puppeteer/issues/367

**Comment by gwharton** [comment]
yes, its a problem with the puppeteer installer by the looks of it. It works if you install puppeteer using `npm install -g puppeteer --unsafe-perm=true` and I can install it globally, however the magepack install is insisting in installing its own copy of puppeteer, and I have no control over the command line arguments it uses. Can I get the magepack install to set `--unsafe-perm=true` when it installs pupeteer?

**Comment by krzksz** [comment]
No, I don't think it is possible, but you can use npm's `--no-optional` to tell magepack to not install puppeteer at all.

**Comment by gwharton** [comment]
Ahh yes the following works to install it globally.

```
npm install -g puppeteer --unsafe-perm=true
npm install -g magepack --no-optional
```

Now i just need to work out why it hangs after `Collecting modules for bundle "category"`

**Comment by krzksz** [comment]
Glad you made some progress! I suggest to go through https://www.npmjs.com/package/magepack#debugging and if you have any issues please add them as separate tickets, thanks!

**Comment by potatskie** [comment]
@gwharton were you able to get a fix where it stuck on Collecting modules for bundle "category"

**Comment by gwharton** [comment]
Yes, as it turns out I had xdebug enabled and my ide had actually dropped into a debug session without me noticing which was hanging the return of the webpage to magepack. You should try manually browsing to the url's that you are passing to magepack. They need to work and return a good webpage without errors when accessed from the machine running magepack. Try wget/curl and inspect the source of the page you get back if you are in console only.
