### ISSUE TITLE
Category page bundle error

### ISSUE THREAD

**Issue by kripals** [magesuite/magepack#85]
Hi,

Tried bundling on magento 2.4, the magepack generate and bundle worked fine and all the bundles are created but when checking the for the bundles on the site the category page is not loading the bundle. Any suggesstions.

**Comment by btekbtek** [comment]
Check:
php bin/magento config:show dev/js/enable_magepack_js_bundling

and set 
php bin/magento config:set dev/js/enable_magepack_js_bundling 1

**Comment by ndthanhnet** [comment]
i'm also having this issue. same commands i used for deployment before but now it just hang

[http]$ nvm use 10 && magepack generate --cms-url="https://www.xxxx.xxx" --category-url="https://www.xxxx.xxx/category" --product-url="https://www.xxxx.xxx/product" && magepack bundle && nvm use 8
Now using node v10.23.1 (npm v6.14.10)
ℹ Collecting bundle modules in the browser.                                                                                             10:33:55
ℹ Collecting modules for bundle "category".   

i haven't deployed for about 10 days, and now magepack is not working on all environments : production, staging, dev and local

pls advise

**Comment by krzksz** [comment]
Have you tried running magepack in debug mode to see why it hangs on
category page? Maybe there are some loading or JS errors.

czw., 18 lut 2021, 11:55 użytkownik Thanh, Nguyen Duy <
notifications@github.com> napisał:

**Comment by ndthanhnet** [comment]
yes, i tried below commands

magepack generate --cms-url="https://www.xxxx.xxx" --category-url="https://www.xxxx.xxx/category" --product-url="https://www.xxxx.xxx/product" -d
magepack generate --cms-url="https://www.xxxx.xxx" --category-url="https://www.xxxx.xxx/category" --product-url="https://www.xxxx.xxx/product" --debug

it either hang or returned this . this is the first time i see this issue, magepack was working properly for months

```
OR  Failed to launch the browser process!                                                                                                                                                                        11:08:38
[367118:367118:0218/110838.384675:ERROR:browser_main_loop.cc(1512)] Unable to open X display.


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md


  [367118:367118:0218/110838.384675:ERROR:browser_main_loop.cc(1512)] Unable to open X display.


  TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

  at onClose (/home/user/.nvm/versions/node/v10.23.0/lib/node_modules/magepack/node_modules/puppeteer/lib/Launcher.js:750:14)
  at ChildProcess.helper.addEventListener (/home/user/.nvm/versions/node/v10.23.0/lib/node_modules/magepack/node_modules/puppeteer/lib/Launcher.js:740:61)
  at ChildProcess.emit (events.js:203:15)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)


```

**Comment by krzksz** [comment]
Above happens because magepack in debug mode will open a browser window
which it can't do on the server CLI. Can you try running the command
locally to see if it works? Maybe it is an issue with the server itself or
something.

czw., 18 lut 2021, 12:10 użytkownik Thanh, Nguyen Duy <
notifications@github.com> napisał:

**Comment by ndthanhnet** [comment]
hi @krzksz , thanks for the hint, i tried again on my mac and i got this . 2 chromium windows poped up (1 blank and 1 for homepage) and asked me for permission, i allowed and chromium closed 2 secs after that.

```
magepack generate --cms-url="https://www.xxxx.xxx/" --category-url="https
://www.xxxx.xxx/sale" --product-url="https://www.xxxx.xxx/product" --debug
ℹ Collecting bundle modules in the browser.                                                 18:44:41                                                                                                        
ℹ Collecting modules for bundle "category".                                                 18:44:41                                                                                                        
                                                   
 ERROR  Protocol error (Runtime.callFunctionOn): Target closed.                             18:45:00  
                                                   
  at Promise (/Users/user/.nvm/versions/node/v10.23.0/lib/node_modules/magepack/node_modules/puppeteer/lib/Connection.js:183:56)
  at new Promise (<anonymous>)                     
  at CDPSession.send (/Users/user/.nvm/versions/node/v10.23.0/lib/node_modules/magepack/node_modules/puppeteer/lib/Connection.js:182:12)                                                               
  at ExecutionContext._evaluateInternal (/Users/user/.nvm/versions/node/v10.23.0/lib/node_modules/magepack/node_modules/puppeteer/lib/ExecutionContext.js:107:44)
  at ExecutionContext.evaluate (/Users/user/.nvm/versions/node/v10.23.0/lib/node_modules/magepack/node_modules/puppeteer/lib/ExecutionContext.js:48:23)                                                
  at ExecutionContext.<anonymous> (/Users/user/.nvm/versions/node/v10.23.0/lib/node_modules/magepack/node_modules/puppeteer/lib/helper.js:112:23)
  at DOMWorld.evaluate (/Users/user/.nvm/versions/node/v10.23.0/lib/node_modules/magepack/node_modules/puppeteer/lib/DOMWorld.js:112:20)                                                               
  at process._tickCallback (internal/process/next_tick.js:68:7)                                                                                                                                               -- ASYNC --                                      
  at Frame.<anonymous> (/Users/user/.nvm/versions/node/v10.23.0/lib/node_modules/magepack/node_modules/puppeteer/lib/helper.js:111:15)
  at Page.evaluate (/Users/user/.nvm/versions/node/v10.23.0/lib/node_modules/magepack/node_modules/puppeteer/lib/Page.js:860:43)
  at Page.<anonymous> (/Users/user/.nvm/versions/node/v10.23.0/lib/node_modules/magepack/node_modules/puppeteer/lib/helper.js:112:23)
  at module.exports (/Users/user/.nvm/versions/node/v10.23.0/lib/node_modules/magepack/lib/generate/collectModules.js:19:16)
  at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by ndthanhnet** [comment]
update : i just tried again and i see category page loaded, another chromium window still blank. on top of chromium, it says Chrome is being contorlled by automated test software.
once pace is loaded, it stays and nothing happened. this is CLI output

```
ℹ Collecting bundle modules in the browser.                                                                                                                                                       18:52:52
ℹ Collecting modules for bundle "category".                                                                                                                                                       18:52:52

 ERROR  Navigation timeout of 30000 ms exceeded                                                                                                                                                   18:53:22

  at Promise.then (/Users/user/.nvm/versions/node/v10.23.0/lib/node_modules/magepack/node_modules/puppeteer/lib/LifecycleWatcher.js:142:21)
  -- ASYNC --
  at Frame.<anonymous> (/Users/user/.nvm/versions/node/v10.23.0/lib/node_modules/magepack/node_modules/puppeteer/lib/helper.js:111:15)
  at Page.goto (/Users/user/.nvm/versions/node/v10.23.0/lib/node_modules/magepack/node_modules/puppeteer/lib/Page.js:672:49)
  at Page.<anonymous> (/Users/user/.nvm/versions/node/v10.23.0/lib/node_modules/magepack/node_modules/puppeteer/lib/helper.js:112:23)
  at Object.category (/Users/user/.nvm/versions/node/v10.23.0/lib/node_modules/magepack/lib/generate/collector/category.js:36:16)
  at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by krzksz** [comment]
Well it looks like Magepack has trouble detecting that your category page
has fully loaded. Are you sure there are no JS errors or 404s for
resources? You can also share the URL if possible so it is easier to check.

**Comment by ndthanhnet** [comment]
hi @krzksz , thank you for the hint. let me try to clean up console errors and try again.

**Comment by ndthanhnet** [comment]
hi @krzksz , you're right about the JS errors, i discovered some errors in console, i fixed them and magepack is now working again. thanks !

**Comment by krzksz** [comment]
Glad I could help. Closing the issue 👍
