### ISSUE TITLE
debug flag throws error

### ISSUE THREAD

**Issue by duckchip** [magesuite/magepack#95]
## Introduction
When i try to run the magepack command with the debug (-d) flag, i get the following error:

## Version
Magepack: v2.4.1
Magento 2.3.6-2

## Issue
 ERROR  Failed to launch the browser process!                                                                                                                                    17:29:15
LaunchProcess: failed to execvp:
/var/www/stagweb/magento2/releases/20210318161826/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/nacl_helper
[10276:10276:0318/172915.562839:ERROR:nacl_fork_delegate_linux.cc(323)] Bad NaCl helper startup ack (0 bytes)
[10274:10274:0318/172915.571635:ERROR:browser_main_loop.cc(1512)] Unable to open X display.

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

  LaunchProcess: failed to execvp:
  releases/20210318161826/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/nacl_helper
  [10276:10276:0318/172915.562839:ERROR:nacl_fork_delegate_linux.cc(323)] Bad NaCl helper startup ack (0 bytes)
  [10274:10274:0318/172915.571635:ERROR:browser_main_loop.cc(1512)] Unable to open X display.

  TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

  at onClose (releases/20210318161826/node_modules/puppeteer/lib/Launcher.js:750:14)
  at ChildProcess.<anonymous> (releases/20210318161826/node_modules/puppeteer/lib/Launcher.js:740:61)
  at ChildProcess.emit (events.js:326:22)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)

**Comment by duckchip** [comment]
Closing this issue since it can be resolved with the following ~/.ssh/config

Host *
    ForwardX11 no

**Comment by HenKun** [comment]
@duckchip May you explain in more detail what do to in order to resolve the issue?
